
/*! @date 27 Maggio 2022 Main Template */

//
////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//                         marcoangelo.r@alice.it                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
//

// #pragma config statements should precede project file includes.
// Use project enums instead of #define for ON and OFF.

//
////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//                  Prototipi delle funzioni                                  //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
//

void main(void);

//
////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//                  Inizializzazione Data Eeprom                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
//

#ifndef _MAIN_H
#define _MAIN_H

#define ENDOFSTRING 0x00

/*! @todo *** Valori da aggiornare */
#define DEFDAYDEC 0x00
#define DEFDAYUNI 0x01
#define DEFDAY 0x01
#define DEFMONTHDEC 0x00
#define DEFMONTHUNI 0x06
#define DEFMONTH 0x06
#define DEFYEARMIG 0x02
#define DEFYEARCENT 0x00
#define DEFYEARDEC 0x02
#define DEFYEARUNI 0x02
#define DEFYEARHIGH 0x20
#define DEFYEARLOW 0x22
/// Define per Numero revisione
#define DEFREVDEC 'R'
#define DEFREVUNI 'C'
#define DEFREVFRAZDEC '1'
#define DEFREVFRAZCENT '0'
#define DEFREVLETTER 'A'
/// Define per Ora revisione
#define DEFORADEC 1
#define DEFORAUNI 8
#define DEFMINDEC 2
#define DEFMINUNI 0

#define DEFTITLE00 'J'
#define DEFTITLE01 'o'
#define DEFTITLE02 'y'
#define DEFTITLE03 ' '
#define DEFTITLE04 'F'
#define DEFTITLE05 'l'
#define DEFTITLE06 'i'
#define DEFTITLE07 'p'
#define DEFTITLE08 'p'
#define DEFTITLE09 'e'
#define DEFTITLE10 'r'
#define DEFTITLE11 ' '
#define DEFTITLE12 ' '
#define DEFTITLE13 ' '
#define DEFTITLE14 ' '
#define DEFTITLE15 ' '
#define DEFTITLE16 ' '
#define DEFTITLE17 ' '
#define DEFTITLE18 ' '
#define DEFTITLE19 ' '
#define DEFTITLE20 ' '
#define DEFTITLE21 ' '
#define DEFTITLE22 ' '
#define DEFTITLE23 ' '
#define DEFTITLE24 ' '
#define LASTTITLE 16
/*! @todo *** End */

#define DEFREVISION00 'R'
#define DEFREVISION01 'e'
#define DEFREVISION02 'v'
#define DEFREVISION03 'i'
#define DEFREVISION04 's'
#define DEFREVISION05 'i'
#define DEFREVISION06 'o'
#define DEFREVISION07 'n'
#define DEFREVISION08 'e'
#define DEFREVISION09 ' '
#define DEFREVISION10 DEFREVDEC
#define DEFREVISION11 DEFREVUNI
#define DEFREVISION12 '.'
#define DEFREVISION13 DEFREVFRAZDEC
#define DEFREVISION14 DEFREVFRAZCENT
#define DEFREVISION15 DEFREVLETTER
#define DEFREVISION16 0
#define DEFREVISION17 ' '
#define DEFREVISION18 ' '
#define DEFREVISION19 ' '
#define DEFREVISION20 ' '
#define DEFREVISION21 ' '
#define DEFREVISION22 ' '
#define DEFREVISION23 ' '
#define DEFREVISION24 ' '

#define DEFDATA00 'D'
#define DEFDATA01 'e'
#define DEFDATA02 'l'
#define DEFDATA03 ':'
#define DEFDATA04 ' '
#define DEFDATA05 (DEFDAYDEC + 48)
#define DEFDATA06 (DEFDAYUNI + 48)
#define DEFDATA07 '-'
#define DEFDATA08 (DEFMONTHDEC + 48)
#define DEFDATA09 (DEFMONTHUNI + 48)
#define DEFDATA10 '-'
#define DEFDATA11 (DEFYEARMIG + 48)
#define DEFDATA12 (DEFYEARCENT + 48)
#define DEFDATA13 (DEFYEARDEC + 48)
#define DEFDATA14 (DEFYEARUNI + 48)
#define DEFDATA15 0
#define DEFDATA16 'O'
#define DEFDATA17 'r'
#define DEFDATA18 'e'
#define DEFDATA19 ' '
#define DEFDATA20 (DEFORADEC + 48) // DEFHH
#define DEFDATA21 (DEFORAUNI + 48)
#define DEFDATA22 ':'
#define DEFDATA23 (DEFMINDEC + 48) // DEFMM
#define DEFDATA24 (DEFMINUNI + 48)

#define DEFCOPYRIGHT00 'A'
#define DEFCOPYRIGHT01 'n'
#define DEFCOPYRIGHT02 'g'
#define DEFCOPYRIGHT03 'e'
#define DEFCOPYRIGHT04 'l'
#define DEFCOPYRIGHT05 'o'
#define DEFCOPYRIGHT06 ' '
#define DEFCOPYRIGHT07 'R'
#define DEFCOPYRIGHT08 'a'
#define DEFCOPYRIGHT09 'g'
#define DEFCOPYRIGHT10 'l'
#define DEFCOPYRIGHT11 'i'
#define DEFCOPYRIGHT12 'a'
#define DEFCOPYRIGHT13 'n'
#define DEFCOPYRIGHT14 't'
#define DEFCOPYRIGHT15 'i'
#define DEFCOPYRIGHT16 0
#define DEFCOPYRIGHT17 ' '
#define DEFCOPYRIGHT18 ' '
#define DEFCOPYRIGHT19 ' '
#define DEFCOPYRIGHT20 ' '
#define DEFCOPYRIGHT21 ' '
#define DEFCOPYRIGHT22 ' '
#define DEFCOPYRIGHT23 ' '
#define DEFCOPYRIGHT24 ' '

const char TITLE[17] = {DEFTITLE00, DEFTITLE01, DEFTITLE02, DEFTITLE03, DEFTITLE04, DEFTITLE05, DEFTITLE06, DEFTITLE07, DEFTITLE08, DEFTITLE09, DEFTITLE10, DEFTITLE11, DEFTITLE12, DEFTITLE13, DEFTITLE14, DEFTITLE15, ENDOFSTRING};
const char REVISION[17] = {DEFREVISION00, DEFREVISION01, DEFREVISION02, DEFREVISION03, DEFREVISION04, DEFREVISION05, DEFREVISION06, DEFREVISION07, DEFREVISION08, DEFREVISION09, DEFREVISION10, DEFREVISION11, DEFREVISION12, DEFREVISION13, DEFREVISION14, DEFREVISION15, ENDOFSTRING};
const char DATE1[17] = {DEFDATA00, DEFDATA01, DEFDATA02, DEFDATA03, DEFDATA04, DEFDATA05, DEFDATA06, DEFDATA07, DEFDATA08, DEFDATA09, DEFDATA10, DEFDATA11, DEFDATA12, DEFDATA13, DEFDATA14, DEFDATA15, ENDOFSTRING};
const char COPYRIGHT[17] = {DEFCOPYRIGHT00, DEFCOPYRIGHT01, DEFCOPYRIGHT02, DEFCOPYRIGHT03, DEFCOPYRIGHT04, DEFCOPYRIGHT05, DEFCOPYRIGHT06, DEFCOPYRIGHT07, DEFCOPYRIGHT08, DEFCOPYRIGHT09, DEFCOPYRIGHT10, DEFCOPYRIGHT11, DEFCOPYRIGHT12, DEFCOPYRIGHT13, DEFCOPYRIGHT14, DEFCOPYRIGHT15, ENDOFSTRING};
const char DATE2[17] = {DEFDATA12, DEFDATA17, DEFDATA18, DEFDATA19, DEFDATA20, DEFDATA21, DEFDATA22, DEFDATA23, DEFDATA24, ENDOFSTRING};
#if defined DEBUGIOREADY
const char TITLEDEBUG[] = "Debug attivo.";
#endif

/*
 * __EEPROM_DATA{DEFCOPYRIGHT00, DEFCOPYRIGHT01, DEFCOPYRIGHT02, DEFCOPYRIGHT03, DEFCOPYRIGHT04, DEFCOPYRIGHT05, DEFCOPYRIGHT06, DEFCOPYRIGHT07};
__EEPROM_DATA{DEFCOPYRIGHT08, DEFCOPYRIGHT09, DEFCOPYRIGHT10, DEFCOPYRIGHT11, DEFCOPYRIGHT12, DEFCOPYRIGHT13, DEFCOPYRIGHT14, DEFCOPYRIGHT15};
__EEPROM_DATA{DEFTITLE00, DEFTITLE01, DEFTITLE02, DEFTITLE03, DEFTITLE04, DEFTITLE05, DEFTITLE06, DEFTITLE07};
__EEPROM_DATA{DEFTITLE08, DEFTITLE09, DEFTITLE10, DEFTITLE11, DEFTITLE12, DEFTITLE13, DEFTITLE14, DEFTITLE15};
__EEPROM_DATA{DEFREVISION00, DEFREVISION01, DEFREVISION02, DEFREVISION03, DEFREVISION04, DEFREVISION05, DEFREVISION06, DEFREVISION07};
__EEPROM_DATA{DEFREVISION08, DEFREVISION09, DEFREVISION10, DEFREVISION11, DEFREVISION12, DEFREVISION13, DEFREVISION14, DEFREVISION15};
__EEPROM_DATA{DEFDATA00, DEFDATA01, DEFDATA02, DEFDATA03, DEFDATA04, DEFDATA05, DEFDATA06, DEFDATA07};
__EEPROM_DATA{DEFDATA08, DEFDATA09, DEFDATA10, DEFDATA11, DEFDATA12, DEFDATA13, DEFDATA14, DEFDATA15}; //  64 Byte
__EEPROM_DATA{DEFCOPYRIGHT00, DEFCOPYRIGHT01, DEFCOPYRIGHT02, DEFCOPYRIGHT03, DEFCOPYRIGHT04, DEFCOPYRIGHT05, DEFCOPYRIGHT06, DEFCOPYRIGHT07};
__EEPROM_DATA{DEFCOPYRIGHT08, DEFCOPYRIGHT09, DEFCOPYRIGHT10, DEFCOPYRIGHT11, DEFCOPYRIGHT12, DEFCOPYRIGHT13, DEFCOPYRIGHT14, DEFCOPYRIGHT15};
__EEPROM_DATA{DEFTITLE00, DEFTITLE01, DEFTITLE02, DEFTITLE03, DEFTITLE04, DEFTITLE05, DEFTITLE06, DEFTITLE07};
__EEPROM_DATA{DEFTITLE08, DEFTITLE09, DEFTITLE10, DEFTITLE11, DEFTITLE12, DEFTITLE13, DEFTITLE14, DEFTITLE15};
__EEPROM_DATA{DEFREVISION00, DEFREVISION01, DEFREVISION02, DEFREVISION03, DEFREVISION04, DEFREVISION05, DEFREVISION06, DEFREVISION07};
__EEPROM_DATA{DEFREVISION08, DEFREVISION09, DEFREVISION10, DEFREVISION11, DEFREVISION12, DEFREVISION13, DEFREVISION14, DEFREVISION15};
__EEPROM_DATA{DEFDATA00, DEFDATA01, DEFDATA02, DEFDATA03, DEFDATA04, DEFDATA05, DEFDATA06, DEFDATA07};
__EEPROM_DATA{DEFDATA08, DEFDATA09, DEFDATA10, DEFDATA11, DEFDATA12, DEFDATA13, DEFDATA14, DEFDATA15}; //  64 Byte
 * */
#endif // closing #if def main.h

//
// E o f
//
